# Generated by Django 5.0.6 on 2025-08-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('youtube_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
