# Generated by Django 5.0.6 on 2025-08-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_aboutvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutvideo',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
