# Generated by Django 5.0.6 on 2025-08-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_aboutvideo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutvideo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
